name: Survival
version: '1.0-SNAPSHOT'
main: de.Palkuchen.survival.Survival
api-version: '1.21'
commands:
  Besteatigung:
  do:
    aliases: ["do1","do2!"]

  Anchor:
  permission:
    aliases:
      - perms:
  skill:
